#!/bin/bash
# check-protected-branches.sh — PreToolUse hook with if: Bash(git push *)
# Generated by codify hooks --preset convention-enforcement
#
# Blocks direct pushes (especially force pushes) to protected branches.
# Protected: main, master, develop, production, release/*

set -u

INPUT=$(cat)
if ! CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null); then
  echo "codify hook error: jq failed to parse input — failing closed" >&2
  exit 2
fi

if [ -z "$CMD" ]; then
  exit 0
fi

# Detect explicit protected branches in the push command
PROTECTED_PATTERN='(^|[[:space:]])(main|master|develop|production|release/[a-zA-Z0-9._/-]+)([[:space:]]|$|:)'

# Detect force-push variants
FORCE_PATTERN='(--force|--force-with-lease|(^|[[:space:]])-f[[:space:]]|(^|[[:space:]])-[a-zA-Z]*f[a-zA-Z]*([[:space:]]|$))'

HAS_PROTECTED=0
HAS_FORCE=0

if echo "$CMD" | grep -qE -- "$PROTECTED_PATTERN"; then
  HAS_PROTECTED=1
fi

if echo "$CMD" | grep -qE -- "$FORCE_PATTERN"; then
  HAS_FORCE=1
fi

# Force-push to protected branch is hard-blocked
if [ "$HAS_PROTECTED" -eq 1 ] && [ "$HAS_FORCE" -eq 1 ]; then
  echo "Blocked by codify convention-enforcement: force-push to protected branch" >&2
  echo "  Command: $CMD" >&2
  echo "  Force-pushing to main/master/develop/production rewrites shared history." >&2
  echo "  If you really need this, run it manually outside the agent session." >&2
  exit 2
fi

# Plain push to protected branch (without --force) is also blocked — encourage PRs
if [ "$HAS_PROTECTED" -eq 1 ]; then
  echo "Blocked by codify convention-enforcement: direct push to protected branch" >&2
  echo "  Command: $CMD" >&2
  echo "  Push to a feature branch and open a Pull Request instead." >&2
  exit 2
fi

exit 0
