#!/bin/bash
# validate-commit-message.sh — PreToolUse hook with if: Bash(git commit *)
# Generated by codify hooks --preset convention-enforcement
#
# Validates commit messages against Conventional Commits 1.0.0:
#   <type>(<optional scope>)<optional !>: <description>
#   types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert
#   description: 1..72 chars, not a trivial placeholder

set -u

INPUT=$(cat)
CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)

if [ -z "$CMD" ]; then
  exit 0
fi

# Extract the message after -m. Supports -m "msg", -m 'msg', --message=msg, --message msg.
# Greedy match for first quoted string after -m or --message.
MSG=$(echo "$CMD" | sed -n -E "s/.*-m[[:space:]]*\"([^\"]*)\".*/\1/p")
if [ -z "$MSG" ]; then
  MSG=$(echo "$CMD" | sed -n -E "s/.*-m[[:space:]]*'([^']*)'.*/\1/p")
fi
if [ -z "$MSG" ]; then
  MSG=$(echo "$CMD" | sed -n -E "s/.*--message[[:space:]]*=?[[:space:]]*\"([^\"]*)\".*/\1/p")
fi

# No -m flag → likely interactive editor commit; skip validation.
if [ -z "$MSG" ]; then
  exit 0
fi

# Take only the first line (header)
HEADER=$(echo "$MSG" | head -n1)

# Trivial placeholder messages
TRIVIAL_PATTERN='^(WIP|wip|tmp|TMP|temp|test|TEST|update|fix|asdf|debug|stuff|things|todo|TODO)$'
if echo "$HEADER" | grep -qE "$TRIVIAL_PATTERN"; then
  echo "Blocked by codify convention-enforcement: trivial commit message" >&2
  echo "  Message: $HEADER" >&2
  echo "  Use Conventional Commits format: <type>(<scope>): <description>" >&2
  echo "  Example: feat(auth): add OAuth2 login" >&2
  exit 2
fi

# Conventional Commits header regex
CC_PATTERN='^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\([a-zA-Z0-9_/.-]+\))?!?: .+'
if ! echo "$HEADER" | grep -qE "$CC_PATTERN"; then
  echo "Blocked by codify convention-enforcement: not a Conventional Commits header" >&2
  echo "  Message: $HEADER" >&2
  echo "  Expected: <type>(<optional scope>)<optional !>: <description>" >&2
  echo "  Valid types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert" >&2
  echo "  Example: feat(auth): add OAuth2 login" >&2
  exit 2
fi

# Header length limit (72 chars is the de-facto standard)
if [ "${#HEADER}" -gt 72 ]; then
  echo "Blocked by codify convention-enforcement: header too long (${#HEADER} > 72 chars)" >&2
  echo "  Header: $HEADER" >&2
  echo "  Move detail into the body (separated by a blank line)." >&2
  exit 2
fi

exit 0
