#!/bin/bash
# lint.sh — auto-format and lint files on Edit/Write
# Generated by codify hooks --preset linting
#
# Reads JSON from stdin, extracts the edited file path, and runs the
# appropriate formatter and/or linter for the file's language.
# Always exits 0 (non-blocking). Tools are invoked only if installed.

set -u

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

# No file path → nothing to lint
if [ -z "$FILE" ] || [ ! -f "$FILE" ]; then
  exit 0
fi

run_if() {
  command -v "$1" >/dev/null 2>&1 && "$@"
}

case "$FILE" in
  *.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs)
    run_if npx prettier --write --log-level silent "$FILE" 2>/dev/null
    run_if npx eslint --fix "$FILE" 2>/dev/null
    ;;
  *.json|*.yaml|*.yml|*.md|*.markdown)
    run_if npx prettier --write --log-level silent "$FILE" 2>/dev/null
    ;;
  *.css|*.scss|*.html)
    run_if npx prettier --write --log-level silent "$FILE" 2>/dev/null
    ;;
  *.py)
    if command -v ruff >/dev/null 2>&1; then
      run_if ruff format "$FILE" 2>/dev/null
      run_if ruff check --fix --quiet "$FILE" 2>/dev/null
    else
      run_if black --quiet "$FILE" 2>/dev/null
    fi
    ;;
  *.go)
    if command -v gofumpt >/dev/null 2>&1; then
      run_if gofumpt -w "$FILE" 2>/dev/null
    else
      run_if gofmt -w "$FILE" 2>/dev/null
    fi
    ;;
  *.rs)
    run_if rustfmt --quiet "$FILE" 2>/dev/null
    ;;
  *.rb)
    run_if rubocop --autocorrect-all --fail-level fatal "$FILE" 2>/dev/null
    ;;
  *.sh|*.bash)
    run_if shfmt -w "$FILE" 2>/dev/null
    ;;
esac

exit 0
