#!/bin/bash
# block-dangerous-commands.sh — PreToolUse hook for Bash matcher
# Generated by codify hooks --preset security-guardrails
#
# Reads JSON from stdin, extracts the bash command, and blocks if it
# matches a known-dangerous pattern. Exit 2 + stderr blocks the call;
# exit 0 lets it proceed.
#
# Limitations (documented honestly — not a security boundary):
#   - regex-based; sophisticated obfuscation can bypass (eval $(echo ...))
#   - heredoc bodies and `find -exec` payloads are not inspected
#   - alternative interpreters (`python -c`, `perl -e`) are not blocked
#   - this stops careless agents, not motivated adversaries
# For stronger guarantees use an AST-based tool like bash-guardian.

set -u

INPUT=$(cat)
if ! CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null); then
  echo "codify hook error: jq failed to parse input — failing closed" >&2
  exit 2
fi

if [ -z "$CMD" ]; then
  exit 0
fi

# Pattern matches use extended regex (grep -E) and are case-insensitive (-i).
# Each line is one independent dangerous pattern.
DANGEROUS=(
  # Recursive deletion of root, home, or current dir
  'rm[[:space:]]+(-[a-zA-Z]*r[a-zA-Z]*f|-[a-zA-Z]*f[a-zA-Z]*r|--recursive[[:space:]]+--force|--force[[:space:]]+--recursive)[[:space:]]+(/|~|\$HOME|/\*|\.[[:space:]]*$|\.[[:space:]]*&)'
  'rm[[:space:]]+-rf[[:space:]]+/'
  'rm[[:space:]]+-rf[[:space:]]+~'
  'rm[[:space:]]+-rf[[:space:]]+\.[[:space:]]*$'
  # World-writable recursive permissions
  'chmod[[:space:]]+(-R|--recursive)[[:space:]]+(777|0777|a\+w|a=rwx)'
  # Force-push to protected branches
  'git[[:space:]]+push[[:space:]]+(--force|--force-with-lease|-f)[[:space:]]+.*[[:space:]]+(main|master|develop|production)'
  'git[[:space:]]+push[[:space:]]+.*(main|master|develop|production).*[[:space:]]+(--force|--force-with-lease|-f)'
  # Pipe-to-shell from untrusted source
  '(curl|wget)[[:space:]]+[^|]*\|[[:space:]]*(bash|sh|zsh)'
  # Fork bomb classic
  ':\(\)\{[[:space:]]*:\|:&[[:space:]]*\};:'
  # Dynamic execution of variables
  'eval[[:space:]]+\$'
  '(^|[[:space:]])source[[:space:]]+\$'
  # Disk write to raw devices
  'dd[[:space:]]+.*of=/dev/(sd|nvme|hd)'
  # Format filesystem
  'mkfs\.[a-z0-9]+[[:space:]]+/dev/'
)

for pattern in "${DANGEROUS[@]}"; do
  if echo "$CMD" | grep -qiE -- "$pattern"; then
    echo "Blocked by codify security-guardrails: command matches dangerous pattern" >&2
    echo "  Pattern: $pattern" >&2
    echo "  Command: $CMD" >&2
    echo "  If this is a false positive, edit .claude/hooks/block-dangerous-commands.sh" >&2
    exit 2
  fi
done

exit 0
