#!/bin/bash
# protect-sensitive-files.sh — PreToolUse hook for Edit|Write matcher
# Generated by codify hooks --preset security-guardrails
#
# Reads JSON from stdin, extracts the target file path, and blocks if
# it matches a sensitive-file pattern (env files, secrets, lockfiles,
# git internals, CI configs, private keys).

set -u

INPUT=$(cat)
if ! FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null); then
  echo "codify hook error: jq failed to parse input — failing closed" >&2
  exit 2
fi

if [ -z "$FILE" ]; then
  exit 0
fi

# Each pattern matches anywhere in the path.
PROTECTED=(
  # Environment files
  '/\.env$'
  '/\.env\.[a-zA-Z0-9._-]+$'
  # Secrets directories
  '/secrets/'
  '/credentials/'
  # Git internals
  '/\.git/'
  # Private keys / certs
  '\.pem$'
  '\.key$'
  '\.p12$'
  '/id_rsa($|\.)'
  '/id_ed25519($|\.)'
  '/id_dsa($|\.)'
  # Lockfiles (changing them outside package manager is usually wrong)
  '/package-lock\.json$'
  '/yarn\.lock$'
  '/pnpm-lock\.yaml$'
  '/Cargo\.lock$'
  '/go\.sum$'
  '/Gemfile\.lock$'
  '/poetry\.lock$'
  # CI/CD configs (require explicit approval)
  '/\.github/workflows/'
  '/\.gitlab-ci\.yml$'
  '/\.circleci/config\.yml$'
)

for pattern in "${PROTECTED[@]}"; do
  if echo "$FILE" | grep -qE -- "$pattern"; then
    echo "Blocked by codify security-guardrails: file matches sensitive pattern" >&2
    echo "  Pattern: $pattern" >&2
    echo "  File:    $FILE" >&2
    echo "  If this edit is intentional, ask the user to make it directly," >&2
    echo "  or edit .claude/hooks/protect-sensitive-files.sh to allow it." >&2
    exit 2
  fi
done

exit 0
