version: '3'

vars:
  APP_NAME: '{{PROJECT_NAME}}'

tasks:
  dev:
    desc: Run in development mode
    cmds:
      - echo "Running javascript project {{PROJECT_NAME}}"

  test:
    desc: Run tests
    cmds:
      - echo "Testing javascript project"

  build:
    desc: Build project
    cmds:
      - echo "Building javascript project"
