package service

import (
	"context"
	"os"
)

// FileWriter defines the interface for writing files.
// Implementations should handle creating parent directories if necessary.
type FileWriter interface {
	WriteFile(path string, content []byte, perm os.FileMode) error
}

// DirectoryManager defines the interface for managing directories.
// Implementations should handle creating parent directories if necessary and checking existence.
type DirectoryManager interface {
	CreateDir(path string, perm os.FileMode) error
	Exists(path string) (bool, error)
}

// LLMProvider defines the interface for LLM-based content generation.
type LLMProvider interface {
	GenerateContext(ctx context.Context, request GenerationRequest) (*GenerationResponse, error)
}

// TemplateLoader defines the interface for loading template guides from disk.
type TemplateLoader interface {
	LoadAll() ([]TemplateGuide, error)
}

// GenerationRequest represents a request to generate context files via LLM.
type GenerationRequest struct {
	ProjectDescription string
	TemplateGuides     []TemplateGuide
	Language           string
	ProjectType        string
	Architecture       string
	Locale             string // Output language: "en", "es", etc.
	ExistingContext    string // For spec mode: content of existing CONTEXT.md + AGENTS.md
	Mode              string // "generate" (default), "spec", or "skills"
	Target            string // For skills mode: target ecosystem ("claude", "codex", "antigravity")
}

// TemplateGuide represents a structural template used as a guide for the LLM.
type TemplateGuide struct {
	Name    string // "agents", "context", "interactions", "constitution", "spec", "plan", "tasks"
	Content string
}

// GeneratedFile represents a single file generated by the LLM.
type GeneratedFile struct {
	Name    string // "AGENTS.md", "CONTEXT.md", etc.
	Content string
}

// GenerationResponse represents the LLM's response with generated files and metadata.
type GenerationResponse struct {
	Files     []GeneratedFile
	Model     string
	TokensIn  int
	TokensOut int
}