package service

import (
	"context"
	"os"
)

// FileWriter defines the interface for writing files.
// Implementations should handle creating parent directories if necessary.
type FileWriter interface {
	WriteFile(path string, content []byte, perm os.FileMode) error
}

// DirectoryManager defines the interface for managing directories.
// Implementations should handle creating parent directories if necessary and checking existence.
type DirectoryManager interface {
	CreateDir(path string, perm os.FileMode) error
	Exists(path string) (bool, error)
}

// LLMProvider defines the interface for LLM-based content generation.
type LLMProvider interface {
	GenerateContext(ctx context.Context, request GenerationRequest) (*GenerationResponse, error)

	// EvaluatePrompt sends a single one-shot prompt and returns the response
	// text plus token counts. Used by lifecycle commands that need a single
	// prompt→response cycle (e.g. `codify audit --with-llm`) instead of the
	// multi-file template-driven flow of GenerateContext.
	//
	// Implementations record usage just like GenerateContext does — the
	// caller does not need to know about the recorder.
	EvaluatePrompt(ctx context.Context, request EvaluationRequest) (*EvaluationResponse, error)
}

// TemplateLoader defines the interface for loading template guides from disk.
type TemplateLoader interface {
	LoadAll() ([]TemplateGuide, error)
}

// GenerationRequest represents a request to generate context files via LLM.
type GenerationRequest struct {
	ProjectDescription string
	TemplateGuides     []TemplateGuide
	Language           string
	ProjectType        string
	Architecture       string
	Locale             string // Output language: "en", "es", etc.
	ExistingContext    string // For spec mode: content of existing CONTEXT.md + AGENTS.md
	Mode              string // "generate" (default), "spec", or "skills"
	Target            string // For skills mode: target ecosystem ("claude", "codex", "antigravity")
	ProjectContext    string // For personalized skills: project description/context
}

// TemplateGuide represents a structural template used as a guide for the LLM.
type TemplateGuide struct {
	Name    string // "agents", "context", "interactions", "constitution", "spec", "plan", "tasks"
	Content string
}

// GeneratedFile represents a single file generated by the LLM.
type GeneratedFile struct {
	Name    string // "AGENTS.md", "CONTEXT.md", etc.
	Content string
}

// GenerationResponse represents the LLM's response with generated files and metadata.
type GenerationResponse struct {
	Files     []GeneratedFile
	Model     string
	TokensIn  int
	TokensOut int
}

// EvaluationRequest is a one-shot prompt evaluation. Used by lifecycle
// commands (audit --with-llm) that need a single response instead of the
// multi-file flow of GenerationRequest.
type EvaluationRequest struct {
	SystemPrompt string
	UserPrompt   string
	Command      string // for usage tracking ("audit", etc.)
	MaxTokens    int    // optional; provider applies a sensible default if 0

	// CacheableSystem signals that the SystemPrompt is stable across
	// successive calls (e.g. multiple files audited or enriched in the same
	// session) and should be marked for prompt caching when the underlying
	// provider supports it. Anthropic uses cache_control ephemeral; Gemini
	// ignores the flag (its caching API has a 4k-token minimum that most
	// of our system prompts do not meet).
	CacheableSystem bool
}

// EvaluationResponse contains the raw text output of a one-shot prompt
// evaluation plus token usage. The caller is responsible for parsing the
// text (e.g. JSON) — providers do not interpret content.
type EvaluationResponse struct {
	Text      string
	Model     string
	TokensIn  int
	TokensOut int
}