#!/bin/bash
# check-protected-branches.sh — PreToolUse hook with if: Bash(git push *)
# Generated by codify hooks --preset convention-enforcement
#
# Blocks direct pushes (especially force pushes) to protected branches.
# Protected: main, master, develop, production, release/*

set -u

INPUT=$(cat)
if ! CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null); then
  echo "codify hook error: jq fallo al parsear input — fail-closed" >&2
  exit 2
fi

if [ -z "$CMD" ]; then
  exit 0
fi

# Detect explicit protected branches in the push command
PROTECTED_PATTERN='(^|[[:space:]])(main|master|develop|production|release/[a-zA-Z0-9._/-]+)([[:space:]]|$|:)'

# Detect force-push variants
FORCE_PATTERN='(--force|--force-with-lease|(^|[[:space:]])-f[[:space:]]|(^|[[:space:]])-[a-zA-Z]*f[a-zA-Z]*([[:space:]]|$))'

HAS_PROTECTED=0
HAS_FORCE=0

if echo "$CMD" | grep -qE -- "$PROTECTED_PATTERN"; then
  HAS_PROTECTED=1
fi

if echo "$CMD" | grep -qE -- "$FORCE_PATTERN"; then
  HAS_FORCE=1
fi

# Force-push to protected branch is hard-blocked
if [ "$HAS_PROTECTED" -eq 1 ] && [ "$HAS_FORCE" -eq 1 ]; then
  echo "Bloqueado por codify convention-enforcement: force-push a branch protegido" >&2
  echo "  Comando: $CMD" >&2
  echo "  Hacer force-push a main/master/develop/production reescribe historia compartida." >&2
  echo "  Si realmente lo necesitas, ejecutalo manualmente fuera de la sesion del agente." >&2
  exit 2
fi

# Plain push to protected branch (without --force) is also blocked — encourage PRs
if [ "$HAS_PROTECTED" -eq 1 ]; then
  echo "Bloqueado por codify convention-enforcement: push directo a branch protegido" >&2
  echo "  Comando: $CMD" >&2
  echo "  Haz push a un feature branch y abre un Pull Request." >&2
  exit 2
fi

exit 0
