#!/bin/bash
# validate-commit-message.sh — PreToolUse hook with if: Bash(git commit *)
# Generated by codify hooks --preset convention-enforcement
#
# Validates commit messages against Conventional Commits 1.0.0:
#   <type>(<optional scope>)<optional !>: <description>
#   types: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert
#   description: 1..72 chars, not a trivial placeholder

set -u

INPUT=$(cat)
if ! CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null); then
  echo "codify hook error: jq fallo al parsear input — fail-closed" >&2
  exit 2
fi

if [ -z "$CMD" ]; then
  exit 0
fi

# Extract the message after -m. Supports -m "msg", -m 'msg', --message=msg, --message msg.
# Greedy match for first quoted string after -m or --message.
MSG=$(echo "$CMD" | sed -n -E "s/.*-m[[:space:]]*\"([^\"]*)\".*/\1/p")
if [ -z "$MSG" ]; then
  MSG=$(echo "$CMD" | sed -n -E "s/.*-m[[:space:]]*'([^']*)'.*/\1/p")
fi
if [ -z "$MSG" ]; then
  MSG=$(echo "$CMD" | sed -n -E "s/.*--message[[:space:]]*=?[[:space:]]*\"([^\"]*)\".*/\1/p")
fi

# No -m flag → likely interactive editor commit; skip validation.
if [ -z "$MSG" ]; then
  exit 0
fi

# Take only the first line (header)
HEADER=$(echo "$MSG" | head -n1)

# Trivial placeholder messages
TRIVIAL_PATTERN='^(WIP|wip|tmp|TMP|temp|test|TEST|update|fix|asdf|debug|stuff|things|todo|TODO)$'
if echo "$HEADER" | grep -qE "$TRIVIAL_PATTERN"; then
  echo "Bloqueado por codify convention-enforcement: mensaje de commit trivial" >&2
  echo "  Mensaje: $HEADER" >&2
  echo "  Usa el formato Conventional Commits: <tipo>(<scope>): <descripcion>" >&2
  echo "  Ejemplo: feat(auth): agrega login OAuth2" >&2
  exit 2
fi

# Conventional Commits header regex
CC_PATTERN='^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\([a-zA-Z0-9_/.-]+\))?!?: .+'
if ! echo "$HEADER" | grep -qE "$CC_PATTERN"; then
  echo "Bloqueado por codify convention-enforcement: no cumple Conventional Commits" >&2
  echo "  Mensaje:  $HEADER" >&2
  echo "  Esperado: <tipo>(<scope opcional>)<! opcional>: <descripcion>" >&2
  echo "  Tipos validos: feat, fix, docs, style, refactor, test, chore, perf, ci, build, revert" >&2
  echo "  Ejemplo: feat(auth): agrega login OAuth2" >&2
  exit 2
fi

# Header length limit (72 chars is the de-facto standard)
if [ "${#HEADER}" -gt 72 ]; then
  echo "Bloqueado por codify convention-enforcement: titulo muy largo (${#HEADER} > 72 chars)" >&2
  echo "  Titulo: $HEADER" >&2
  echo "  Mueve el detalle al cuerpo (separado por una linea en blanco)." >&2
  exit 2
fi

exit 0
