package commands

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"
	"github.com/jorelcb/codify/internal/application/query"
	"github.com/jorelcb/codify/internal/infrastructure/persistence/memory"
)

// NewListCmd creates the list command
func NewListCmd() *cobra.Command {
	var outputDir string

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List generated projects",
		Long: `List all projects that have been generated by codify.

This command scans the output directory and displays all generated projects
with their metadata (language, type, architecture, creation date).

Examples:
  # List projects in default output directory
  codify list

  # List projects in custom directory
  codify list --output-dir ./my-projects`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runList(outputDir)
		},
	}

	cmd.Flags().StringVarP(&outputDir, "output-dir", "o", "./output", "Output directory to scan")

	return cmd
}

func runList(outputDir string) error {
	ctx := context.Background()

	// Initialize repository (in-memory for now)
	projectRepo := memory.NewProjectRepository()

	// Initialize query
	listQuery := query.NewListProjectsQuery(projectRepo)

	// Execute query
	result, err := listQuery.Execute(ctx)
	if err != nil {
		return fmt.Errorf("failed to list projects: %w", err)
	}

	// Display results
	fmt.Printf("Projects in: %s\n\n", outputDir)

	if result.Total == 0 {
		fmt.Println("No projects found.")
		fmt.Println()
		fmt.Println("Generate your first project with:")
		fmt.Println("  codify generate my-project -l go -t api")
		return nil
	}

	fmt.Printf("Found %d project(s):\n\n", result.Total)

	for i, proj := range result.Projects {
		fmt.Printf("%d. %s\n", i+1, proj.Name)
		fmt.Printf("   ID: %s\n", proj.ID)
		fmt.Printf("   Language: %s | Type: %s | Architecture: %s\n",
			proj.Language, proj.Type, proj.Architecture)
		fmt.Printf("   Output: %s\n", proj.OutputPath)
		fmt.Printf("   Created: %s\n", proj.CreatedAt.Format("2006-01-02 15:04:05"))
		if len(proj.Capabilities) > 0 {
			fmt.Printf("   Capabilities: %v\n", proj.Capabilities)
		}
		fmt.Println()
	}

	return nil
}