package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	root "github.com/jorelcb/codify"
	"github.com/jorelcb/codify/internal/application/command"
	"github.com/jorelcb/codify/internal/application/dto"
	"github.com/jorelcb/codify/internal/infrastructure/filesystem"
	"github.com/jorelcb/codify/internal/infrastructure/llm"
	infratemplate "github.com/jorelcb/codify/internal/infrastructure/template"
)

// specTemplateMapping maps spec template file names to their guide names.
var specTemplateMapping = map[string]string{
	"constitution.template": "constitution",
	"spec.template":         "spec",
	"plan.template":         "plan",
	"tasks.template":        "tasks",
}

// specParams agrupa todos los parámetros del comando spec.
type specParams struct {
	fromContext string
	output     string
	model      string
	locale     string
}

// NewSpecCmd creates the spec command
func NewSpecCmd() *cobra.Command {
	var p specParams

	cmd := &cobra.Command{
		Use:   "spec <project-name>",
		Short: "Generate SDD specification files from existing context",
		Long: `Generate spec-driven development files from previously generated context:
  - CONSTITUTION.md - Project DNA: stack, conventions, constraints, principles
  - SPEC.md - Feature specifications with acceptance criteria
  - PLAN.md - Technical design and architecture decisions
  - TASKS.md - Implementation task breakdown with dependencies

Requires existing context generated by the 'generate' command.
Requires ANTHROPIC_API_KEY (for Claude) or GEMINI_API_KEY (for Gemini) environment variable.

When run in a terminal, interactive menus guide you through options not provided via flags.

Examples:
  # Generate specs from context in current directory
  codify spec my-api --from-context .

  # Generate specs to a custom directory
  codify spec my-api --from-context ./context-dir/ --output ./specs-dir/

  # With custom model
  codify spec my-api --from-context . --model claude-sonnet-4-6`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			explicit := make(map[string]bool)
			cmd.Flags().Visit(func(f *pflag.Flag) {
				explicit[f.Name] = true
			})

			return runSpecInteractive(args[0], p, explicit)
		},
	}

	cmd.Flags().StringVar(&p.fromContext, "from-context", "", "Path to existing context directory (required)")
	_ = cmd.MarkFlagRequired("from-context")
	cmd.Flags().StringVarP(&p.output, "output", "o", "", "Output directory (default: same as --from-context)")
	cmd.Flags().StringVarP(&p.model, "model", "m", "", "LLM model (default: claude-sonnet-4-6, or gemini-3.1-pro-preview)")
	cmd.Flags().StringVar(&p.locale, "locale", defaultLocale, "Output language: en (English) or es (Spanish)")

	return cmd
}

func runSpecInteractive(projectName string, p specParams, explicit map[string]bool) error {
	interactive := isInteractive()
	var err error

	// 1. Resolve model
	if !explicit["model"] && interactive {
		p.model, err = promptModel()
		if err != nil {
			return err
		}
	}

	// 2. Resolve locale
	if !explicit["locale"] && interactive {
		p.locale, err = promptLocale()
		if err != nil {
			return err
		}
	}

	// 3. Resolve output
	if !explicit["output"] && interactive {
		defaultOutput := p.fromContext
		if defaultOutput == "" {
			defaultOutput = "."
		}
		p.output, err = promptInput("Output directory", defaultOutput)
		if err != nil {
			return err
		}
	}

	return runSpec(projectName, p.fromContext, p.output, p.model, p.locale)
}

func runSpec(projectName, fromContext, output, model, locale string) error {
	if output == "" {
		output = fromContext
	}
	ctx := context.Background()

	// 1. Resolve API key for the selected provider
	apiKey, err := llm.ResolveAPIKey(model)
	if err != nil {
		return err
	}

	// 2. Read existing context files
	contextReader := filesystem.NewContextReader()
	existingContext, err := contextReader.ReadExistingContext(fromContext)
	if err != nil {
		return fmt.Errorf("failed to read existing context: %w", err)
	}

	// 3. Load spec templates
	templateLoader := infratemplate.NewFileSystemTemplateLoaderWithMapping(root.TemplatesFS, filepath.Join("templates", locale, "spec"), specTemplateMapping)
	guides, err := templateLoader.LoadAll()
	if err != nil {
		return fmt.Errorf("failed to load spec templates: %w", err)
	}

	// 4. Initialize LLM provider
	provider, err := llm.NewProvider(ctx, model, apiKey, os.Stdout)
	if err != nil {
		return fmt.Errorf("failed to create LLM provider: %w", err)
	}

	// 5. Initialize infrastructure
	fileWriter := filesystem.NewFileWriter()
	dirManager := filesystem.NewDirectoryManager()

	// 6. Create command
	specCmd := command.NewGenerateSpecCommand(provider, fileWriter, dirManager)

	// 7. Build config
	config := &dto.SpecConfig{
		ProjectName:     projectName,
		FromContextPath: fromContext,
		OutputPath:      output,
		Model:           model,
		Locale:          locale,
	}

	// 8. Show progress
	fmt.Printf("Generating specs for: %s\n", projectName)
	fmt.Printf("  From context: %s\n", fromContext)
	fmt.Printf("  Model: %s\n", llm.DefaultModel(model))
	fmt.Printf("  Locale: %s\n", locale)
	fmt.Println()
	fmt.Println("Generating spec files via LLM API...")

	// 9. Execute
	result, err := specCmd.Execute(ctx, config, existingContext, guides)
	if err != nil {
		return fmt.Errorf("spec generation failed: %w", err)
	}

	// 10. Update AGENTS.md with specs references
	if err := updateAgentsWithSpecsRef(output, locale); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not update AGENTS.md with specs reference: %v\n", err)
	}

	// 11. Show results
	fmt.Println()
	fmt.Println("Spec files generated successfully!")
	fmt.Printf("  Output: %s\n", result.OutputPath)
	fmt.Printf("  Model: %s\n", result.Model)
	fmt.Printf("  Tokens: %d in / %d out\n", result.TokensIn, result.TokensOut)
	fmt.Println()
	fmt.Println("Generated files:")
	for _, f := range result.GeneratedFiles {
		fmt.Printf("  - %s\n", f)
	}

	return nil
}

// updateAgentsWithSpecsRef appends specs file references to AGENTS.md if not already present.
func updateAgentsWithSpecsRef(fromContextPath string, locale string) error {
	agentsPath := filepath.Join(fromContextPath, "AGENTS.md")

	content, err := os.ReadFile(agentsPath)
	if err != nil {
		// AGENTS.md might not exist — skip silently
		return nil
	}

	// Check if specs reference already exists (idempotent)
	if strings.Contains(string(content), "specs/") {
		return nil
	}

	var specsRef string
	if locale == "es" {
		specsRef = "\n## Especificaciones\n\n" +
			"- Constitucion del proyecto: `specs/CONSTITUTION.md`\n" +
			"- Especificaciones de features: `specs/SPEC.md`\n" +
			"- Diseno tecnico y plan: `specs/PLAN.md`\n" +
			"- Desglose de tareas: `specs/TASKS.md`\n"
	} else {
		specsRef = "\n## Specifications\n\n" +
			"- Project constitution: `specs/CONSTITUTION.md`\n" +
			"- Feature specifications: `specs/SPEC.md`\n" +
			"- Technical design and plan: `specs/PLAN.md`\n" +
			"- Task breakdown: `specs/TASKS.md`\n"
	}

	updated := string(content) + specsRef
	return os.WriteFile(agentsPath, []byte(updated), 0644)
}
