package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/jorelcb/ai-context-generator/internal/application/command"
	"github.com/jorelcb/ai-context-generator/internal/application/dto"
	"github.com/jorelcb/ai-context-generator/internal/infrastructure/filesystem"
	"github.com/jorelcb/ai-context-generator/internal/infrastructure/llm"
	infratemplate "github.com/jorelcb/ai-context-generator/internal/infrastructure/template"
)

// specTemplateMapping maps spec template file names to their guide names.
var specTemplateMapping = map[string]string{
	"constitution.template": "constitution",
	"spec.template":         "spec",
	"plan.template":         "plan",
	"tasks.template":        "tasks",
}

// NewSpecCmd creates the spec command
func NewSpecCmd() *cobra.Command {
	var (
		fromContext string
		model       string
	)

	cmd := &cobra.Command{
		Use:   "spec <project-name>",
		Short: "Generate SDD specification files from existing context",
		Long: `Generate spec-driven development files from previously generated context:
  - CONSTITUTION.md - Project DNA: stack, conventions, constraints, principles
  - SPEC.md - Feature specifications with acceptance criteria
  - PLAN.md - Technical design and architecture decisions
  - TASKS.md - Implementation task breakdown with dependencies

Requires existing context generated by the 'generate' command.
Requires ANTHROPIC_API_KEY environment variable.

Examples:
  # Generate specs from existing context
  ai-context-generator spec my-api --from-context ./output/my-api/

  # With custom model
  ai-context-generator spec my-api --from-context ./output/my-api/ --model claude-sonnet-4-6`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			projectName := args[0]
			return runSpec(projectName, fromContext, model)
		},
	}

	cmd.Flags().StringVar(&fromContext, "from-context", "", "Path to existing output directory (required)")
	_ = cmd.MarkFlagRequired("from-context")
	cmd.Flags().StringVarP(&model, "model", "m", "", "Claude model to use (default: claude-sonnet-4-6)")

	return cmd
}

func runSpec(projectName, fromContext, model string) error {
	ctx := context.Background()

	// 1. Check API key
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		return fmt.Errorf("ANTHROPIC_API_KEY environment variable is required")
	}

	// 2. Read existing context files
	contextReader := filesystem.NewContextReader()
	existingContext, err := contextReader.ReadExistingContext(fromContext)
	if err != nil {
		return fmt.Errorf("failed to read existing context: %w", err)
	}

	// 3. Load spec templates
	templateLoader := infratemplate.NewFileSystemTemplateLoaderWithMapping("templates/spec", specTemplateMapping)
	guides, err := templateLoader.LoadAll()
	if err != nil {
		return fmt.Errorf("failed to load spec templates: %w", err)
	}

	// 4. Initialize LLM provider
	provider := llm.NewAnthropicProvider(apiKey, model, os.Stdout)

	// 5. Initialize infrastructure
	fileWriter := filesystem.NewFileWriter()
	dirManager := filesystem.NewDirectoryManager()

	// 6. Create command
	specCmd := command.NewGenerateSpecCommand(provider, fileWriter, dirManager)

	// 7. Build config
	outputPath := filepath.Join("output", projectName)
	config := &dto.SpecConfig{
		ProjectName:     projectName,
		FromContextPath: fromContext,
		OutputPath:      outputPath,
		Model:           model,
	}

	// 8. Show progress
	fmt.Printf("Generating specs for: %s\n", projectName)
	fmt.Printf("  From context: %s\n", fromContext)
	usedModel := model
	if usedModel == "" {
		usedModel = "claude-sonnet-4-6"
	}
	fmt.Printf("  Model: %s\n", usedModel)
	fmt.Println()
	fmt.Println("Generating spec files via Claude API...")

	// 9. Execute
	result, err := specCmd.Execute(ctx, config, existingContext, guides)
	if err != nil {
		return fmt.Errorf("spec generation failed: %w", err)
	}

	// 10. Show results
	fmt.Println()
	fmt.Println("Spec files generated successfully!")
	fmt.Printf("  Output: %s\n", result.OutputPath)
	fmt.Printf("  Model: %s\n", result.Model)
	fmt.Printf("  Tokens: %d in / %d out\n", result.TokensIn, result.TokensOut)
	fmt.Println()
	fmt.Println("Generated files:")
	for _, f := range result.GeneratedFiles {
		fmt.Printf("  - %s\n", f)
	}

	return nil
}
