package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	root "github.com/jorelcb/ai-context-generator"
	"github.com/jorelcb/ai-context-generator/internal/application/command"
	"github.com/jorelcb/ai-context-generator/internal/application/dto"
	"github.com/jorelcb/ai-context-generator/internal/infrastructure/filesystem"
	"github.com/jorelcb/ai-context-generator/internal/infrastructure/llm"
	infratemplate "github.com/jorelcb/ai-context-generator/internal/infrastructure/template"
)

// specTemplateMapping maps spec template file names to their guide names.
var specTemplateMapping = map[string]string{
	"constitution.template": "constitution",
	"spec.template":         "spec",
	"plan.template":         "plan",
	"tasks.template":        "tasks",
}

// NewSpecCmd creates the spec command
func NewSpecCmd() *cobra.Command {
	var (
		fromContext string
		model       string
		locale      string
	)

	cmd := &cobra.Command{
		Use:   "spec <project-name>",
		Short: "Generate SDD specification files from existing context",
		Long: `Generate spec-driven development files from previously generated context:
  - CONSTITUTION.md - Project DNA: stack, conventions, constraints, principles
  - SPEC.md - Feature specifications with acceptance criteria
  - PLAN.md - Technical design and architecture decisions
  - TASKS.md - Implementation task breakdown with dependencies

Requires existing context generated by the 'generate' command.
Requires ANTHROPIC_API_KEY (for Claude) or GEMINI_API_KEY (for Gemini) environment variable.

Examples:
  # Generate specs from existing context
  ai-context-generator spec my-api --from-context ./output/my-api/

  # With custom model
  ai-context-generator spec my-api --from-context ./output/my-api/ --model claude-sonnet-4-6`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			projectName := args[0]
			return runSpec(projectName, fromContext, model, locale)
		},
	}

	cmd.Flags().StringVar(&fromContext, "from-context", "", "Path to existing output directory (required)")
	_ = cmd.MarkFlagRequired("from-context")
	cmd.Flags().StringVarP(&model, "model", "m", "", "LLM model (default: claude-sonnet-4-6, or gemini-3.1-pro-preview)")
	cmd.Flags().StringVar(&locale, "locale", defaultLocale, "Output language: en (English) or es (Spanish)")

	return cmd
}

func runSpec(projectName, fromContext, model, locale string) error {
	ctx := context.Background()

	// 1. Resolve API key for the selected provider
	apiKey, err := llm.ResolveAPIKey(model)
	if err != nil {
		return err
	}

	// 2. Read existing context files
	contextReader := filesystem.NewContextReader()
	existingContext, err := contextReader.ReadExistingContext(fromContext)
	if err != nil {
		return fmt.Errorf("failed to read existing context: %w", err)
	}

	// 3. Load spec templates
	templateLoader := infratemplate.NewFileSystemTemplateLoaderWithMapping(root.TemplatesFS, filepath.Join("templates", locale, "spec"), specTemplateMapping)
	guides, err := templateLoader.LoadAll()
	if err != nil {
		return fmt.Errorf("failed to load spec templates: %w", err)
	}

	// 4. Initialize LLM provider
	provider, err := llm.NewProvider(ctx, model, apiKey, os.Stdout)
	if err != nil {
		return fmt.Errorf("failed to create LLM provider: %w", err)
	}

	// 5. Initialize infrastructure
	fileWriter := filesystem.NewFileWriter()
	dirManager := filesystem.NewDirectoryManager()

	// 6. Create command
	specCmd := command.NewGenerateSpecCommand(provider, fileWriter, dirManager)

	// 7. Build config
	outputPath := filepath.Join("output", projectName)
	config := &dto.SpecConfig{
		ProjectName:     projectName,
		FromContextPath: fromContext,
		OutputPath:      outputPath,
		Model:           model,
		Locale:          locale,
	}

	// 8. Show progress
	fmt.Printf("Generating specs for: %s\n", projectName)
	fmt.Printf("  From context: %s\n", fromContext)
	fmt.Printf("  Model: %s\n", llm.DefaultModel(model))
	fmt.Printf("  Locale: %s\n", locale)
	fmt.Println()
	fmt.Println("Generating spec files via Claude API...")

	// 9. Execute
	result, err := specCmd.Execute(ctx, config, existingContext, guides)
	if err != nil {
		return fmt.Errorf("spec generation failed: %w", err)
	}

	// 10. Update AGENTS.md with specs references
	if err := updateAgentsWithSpecsRef(fromContext, locale); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not update AGENTS.md with specs reference: %v\n", err)
	}

	// 11. Show results
	fmt.Println()
	fmt.Println("Spec files generated successfully!")
	fmt.Printf("  Output: %s\n", result.OutputPath)
	fmt.Printf("  Model: %s\n", result.Model)
	fmt.Printf("  Tokens: %d in / %d out\n", result.TokensIn, result.TokensOut)
	fmt.Println()
	fmt.Println("Generated files:")
	for _, f := range result.GeneratedFiles {
		fmt.Printf("  - %s\n", f)
	}

	return nil
}

// updateAgentsWithSpecsRef appends specs file references to AGENTS.md if not already present.
func updateAgentsWithSpecsRef(fromContextPath string, locale string) error {
	agentsPath := filepath.Join(fromContextPath, "AGENTS.md")

	content, err := os.ReadFile(agentsPath)
	if err != nil {
		// AGENTS.md might not exist — skip silently
		return nil
	}

	// Check if specs reference already exists (idempotent)
	if strings.Contains(string(content), "specs/") {
		return nil
	}

	var specsRef string
	if locale == "es" {
		specsRef = "\n## Especificaciones\n\n" +
			"- Constitucion del proyecto: `specs/CONSTITUTION.md`\n" +
			"- Especificaciones de features: `specs/SPEC.md`\n" +
			"- Diseno tecnico y plan: `specs/PLAN.md`\n" +
			"- Desglose de tareas: `specs/TASKS.md`\n"
	} else {
		specsRef = "\n## Specifications\n\n" +
			"- Project constitution: `specs/CONSTITUTION.md`\n" +
			"- Feature specifications: `specs/SPEC.md`\n" +
			"- Technical design and plan: `specs/PLAN.md`\n" +
			"- Task breakdown: `specs/TASKS.md`\n"
	}

	updated := string(content) + specsRef
	return os.WriteFile(agentsPath, []byte(updated), 0644)
}
