#!/bin/bash
# setup.sh - Setup común para tests del AI Context Generator
set -euo pipefail

# Variables globales para testing
export AI_GENERATOR_ROOT
export TEST_OUTPUT_DIR
export ORIGINAL_PWD

# Inicializar entorno de testing
setup_test_environment() {
    # Guardar directorio actual
    ORIGINAL_PWD=$(pwd)
    
    # Encontrar la raíz del proyecto
    if [ -f "Taskfile.yml" ] && [ -d "templates" ]; then
        AI_GENERATOR_ROOT=$(pwd)
    elif [ -f "../Taskfile.yml" ] && [ -d "../templates" ]; then
        AI_GENERATOR_ROOT=$(cd .. && pwd)
    elif [ -f "../../Taskfile.yml" ] && [ -d "../../templates" ]; then
        AI_GENERATOR_ROOT=$(cd ../.. && pwd)
    else
        echo "Error: Could not find AI Context Generator root directory"
        exit 1
    fi
    
    # Cambiar al directorio raíz
    cd "$AI_GENERATOR_ROOT"
    
    # Crear directorio temporal para outputs de test
    TEST_OUTPUT_DIR=$(mktemp -d -t ai-context-generator-test.XXXXXX)
    
    # Verificar dependencias
    check_dependencies
    
    echo "Test environment setup complete:"
    echo "  Root: $AI_GENERATOR_ROOT"
    echo "  Test output: $TEST_OUTPUT_DIR"
}

# Verificar que todas las dependencias estén disponibles
check_dependencies() {
    local missing_deps=""
    
    for cmd in task jq git; do
        if ! command -v "$cmd" &> /dev/null; then
            missing_deps="$missing_deps $cmd"
        fi
    done
    
    if [ -n "$missing_deps" ]; then
        echo "Error: Missing required dependencies:$missing_deps"
        echo "Please install them before running tests"
        exit 1
    fi
}

# Limpiar entorno después de tests
cleanup_test_environment() {
    # Restaurar directorio original
    cd "$ORIGINAL_PWD"
    
    # Limpiar directorio temporal si existe
    if [ -n "${TEST_OUTPUT_DIR:-}" ] && [ -d "$TEST_OUTPUT_DIR" ]; then
        rm -rf "$TEST_OUTPUT_DIR"
    fi
}

# Crear proyecto de test temporal usando el generador
create_test_project() {
    local project_name="$1"
    local language="$2"
    local project_type="$3"
    local ai_provider="${4:-openai}"
    
    # Crear configuración JSON temporal
    local config_file="$TEST_OUTPUT_DIR/test_config.json"
    cat > "$config_file" << EOF
{
    "project_name": "$project_name",
    "language": "$language",
    "project_type": "$project_type",
    "ai_provider": "$ai_provider",
    "description": "Test project generated by AI Context Generator test suite",
    "capabilities": []
}
EOF
    
    # Generar proyecto usando la configuración
    env AI_GENERATOR_OUTPUT="$TEST_OUTPUT_DIR" \
        task generate:from:config CONFIG_FILE="$config_file" > /dev/null 2>&1
    
    echo "$TEST_OUTPUT_DIR/$project_name"
}

# Verificar que un proyecto generado tiene la estructura correcta
verify_basic_project_structure() {
    local project_path="$1"
    local language="$2"
    
    # Verificar directorios básicos
    [ -d "$project_path/context" ] || return 1
    [ -d "$project_path/internal" ] || return 1
    
    # Verificar archivos de contexto
    [ -f "$project_path/context/01_PROMPT.md" ] || return 1
    [ -f "$project_path/context/02_CONTEXT.md" ] || return 1
    [ -f "$project_path/context/03_SCAFFOLDING.md" ] || return 1
    [ -f "$project_path/context/04_INTERACTIONS_LOG.md" ] || return 1
    
    # Verificar Taskfile
    [ -f "$project_path/Taskfile.yml" ] || return 1
    
    # Verificar archivos específicos del lenguaje
    case "$language" in
        "go")
            [ -f "$project_path/go.mod" ] || return 1
            [ -d "$project_path/cmd" ] || return 1
            ;;
        "javascript")
            [ -f "$project_path/package.json" ] || return 1
            [ -d "$project_path/src" ] || return 1
            ;;
        "python")
            [ -f "$project_path/pyproject.toml" ] || return 1
            [ -d "$project_path/src" ] || return 1
            ;;
    esac
    
    return 0
}

# Función para validar que no hay placeholders sin reemplazar
validate_no_placeholders() {
    local project_path="$1"
    
    # Buscar placeholders no reemplazados
    local placeholder_files
    placeholder_files=$(find "$project_path" -type f \( -name "*.md" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" \) -exec grep -l "{{.*}}" {} \; 2>/dev/null || true)
    
    if [ -n "$placeholder_files" ]; then
        echo "Found unreplaced placeholders in:"
        echo "$placeholder_files"
        return 1
    fi
    
    return 0
}

# Trap para limpieza automática
trap cleanup_test_environment EXIT